/**
 * AiTakeBadge — reusable "AI" indicator for content generated by an LLM.
 *
 * Marks a line as model-written so readers distinguish data vs. opinion.
 * Used by MatchupsTab (F2-2), Power Rankings (F2-3), Awards (F2-5).
 */
export function AiTakeBadge() {
  return (
    <span
      className="ml-1 inline-flex h-4 items-center rounded border border-amber-700/50 bg-amber-950/30 px-1 text-[10px] font-bold uppercase leading-none text-amber-400"
      title="AI-generated takeaway — may reflect model opinion, not fact"
    >
      AI
    </span>
  )
}
